# https://github.com/jenkinsci/.github/blob/master/.github/release-drafter.adoc
_extends: .github
# We are using semver here
version-template: $MAJOR.$MINOR.$PATCH
tag-template: collapsing-console-sections-$NEXT_MINOR_VERSION

